### ISSUE TITLE
"Upgrade to Pro" even if you purchase pro 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#875] opened 2022-03-23 10:14 UTC
**Describe the bug**
The issue is with the main plugin. See the attached screen shot. It looks like I haven't purchased Pro, but I have (note the "Upgrade to Pro" message.)
https://secure.helpscout.net/conversation/1822079513/45556/

**Comment by mplusb** [comment] 2022-05-31 10:20
this is closed, but the issue still happens and users are still complaining.

The problem is that there are too much advetisements for the paid version, and they don't disapear after purchasing the pro version.
The worst case is that you have to install all plugins to get rid of some super invasive nags.

In my opinion these are bad design, and I would recommend making huge change to the main application.
Such as:

1. Make rid of all advertisements for the paid version if at least one plug in is installed.
2. Let the user download plugins he he has paid, and do not invite him to upgrade
3. Do not force the user to install all plugins, and remove the "install/buy Pro" features from every window.
(for example the Amazon plugin and the Download Page are ultra invasive and it's not even possible to reduce them without installing the plugin)

Or, let the paid user download a pro version of the main application that is clean (I am sure this is what everyone is expecting).
I hope I am not the only one making such feedback.
Usualy on wordpress when you buy and pay the price for a plugin, you want to feel you bought it and you're valued as a customer.
Here you feel you're still using the free plugin on every page and it's not only anoying, but also almost offensive (bad marketing choice).

**Comment by razvanaldea89** [comment] 2022-11-15 17:04
Going to close this and keep https://github.com/WPChill/download-monitor/issues/939 open so that in the near future we'll remake the license system to be smarter.

**Closed by razvanaldea89** 2022-11-15 17:04 UTC
Labels: Bug, needs testing
