### ISSUE TITLE
Multiple files download and ZIP

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#728] opened 2021-09-01 07:51 UTC
Multiple files download : https://github.com/cristianraiber/js-multi-file-download/blob/master/src/main/resources/static/multidownload.js

ZIP : https://stackoverflow.com/questions/1754352/download-multiple-files-as-a-zip-file-using-php

**Comment by cristianraiber** [comment] 2022-10-29 12:37
Duplicate of: #684

**Closed** 2022-10-29 12:38 UTC
Labels: Duplicate
