### ISSUE TITLE
downloads are not counted anymore

### ISSUE THREAD

**Issue by senlin** [WPChill/download-monitor#1307] opened 2023-07-21 11:36 UTC
Previously downloads were counted, but they no longer are

**To Reproduce**
1. add a download and publish it
2. go to a new browser where not logged in as admin
3. download the file
4. go back to the first browser where logged in as admin and go to the downloads page, counter has not changed
**Expected behavior**
The counter should increase after each download, but it no longer does

**Extensions installed and activated:**
none

**Additional context**
Previously this was working, but even after rolling back to previous versions (I believe it was still working on v4.7.78) I cannot get the downloads count to update anymore.

**Comment by razvanaldea89** [comment] 2023-07-21 12:25
Hello @senlin ,

A link to a page where you have some downloads would help, as I can't reproduce the issue.

Warmly,
Razvan

**Comment by senlin** [comment] 2023-07-21 13:37
Hello @razvanaldea89 

Thanks for your reply.

I can give you admin access, but need your email address for that or another way to privately contact you.

Cheers,
Pieter

**Comment by cristianraiber** [comment] 2023-07-21 13:59
> Hello @razvanaldea89
> 
> Thanks for your reply.
> 
> I can give you admin access, but need your email address for that or another way to privately contact you.
> 
> Cheers, Pieter

Just use our contact form here: https://www.download-monitor.com/contact/

**Comment by cristianraiber** [comment] 2023-07-21 15:01
We'll continue the conversation there. I'll go ahead and close this ticket.

**Closed by cristianraiber** 2023-07-21 15:01 UTC
Labels: Bug

**Comment by Dawa406** [comment] 2023-11-01 10:20
> Previously downloads were counted, but they no longer are
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. add a download and publish it
> 2. go to a new browser where not logged in as admin
> 3. download the file
> 4. go back to the first browser where logged in as admin and go to the downloads page, counter has not changed
>    **Expected behavior**
>    The counter should increase after each download, but it no longer does
> 
> **Extensions installed and activated:** none
> 
> **Additional context** Previously this was working, but even after rolling back to previous versions (I believe it was still working on v4.7.78) I cannot get the downloads count to update anymore.

Hello I have also faced the same issue, 
Has you problem been solved?
If yes, how have you been able to solve the download counter issue...
Thank you...

**Comment by senlin** [comment] 2023-11-01 11:16
Yes, I solved it, by sending an email as instructed. You could do the same no?

**Comment by Dawa406** [comment] 2023-11-11 16:26
> Yes, I solved it, by sending an email as instructed. You could do the same no?

Thank you for the kind response
