### ISSUE TITLE
 Latest version of the plugin kills my product downloads

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1078] opened 2022-10-10 13:28 UTC
**Describe the bug**
Latest version of the plugin kills my product downloads. I reverted back to old looks. This is the error with new version: 2022/10/07 18:24:45 [error] 122144#122144: *1328679 upstream prematurely closed FastCGI request while reading upstream, client: 217.103.80.70, server: mydomain.com, request: "GET /download/editor-full-pc/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-wwwmydomaincom.sock:", host: "mydomain.com:26750", referrer: "https://mydomain.com/" 2022/10/07 18:24:44 [error] 122144#122144: *1328679 FastCGI sent in stderr: "PHP message: PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 165679104 bytes) in /www/wwwmydomaincom_171/public/wp-content/plugins/download-monitor/src/DownloadHandler.php on line 805" while reading response header from upstream, client: 217.103.80.70, server: mydomain.com, request: "GET /download/editor-full-pc/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-wwwmydomaincom.sock:", host: "mydomain.com:26750", referrer: "https://mydomain.com/" download size > 350mb.

https://secure.helpscout.net/conversation/2031828452/50431?folderId=4656047

**Comment by razvanaldea89** [comment] 2022-10-14 06:41
Similar/duplicate of https://github.com/WPChill/download-monitor/issues/1084

**Closed by razvanaldea89** 2022-10-14 06:41 UTC
Labels: Bug
