### ISSUE TITLE
automatically create no access page 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1249] opened 2023-04-05 06:52 UTC
**Is your feature request related to a problem? Please describe.**
When you install DLM it would be great if a No Access page would be created and set automatically in Downloads > Settings > Advanced > No Access page. 
This happens when you install the DLM Downloading Page extension.

**Comment by TeoAlex** [comment] 2023-07-20 14:50
Duplicate of this https://github.com/WPChill/download-monitor/issues/1305

**Closed by TeoAlex** 2023-07-20 14:50 UTC
Labels: Duplicate, enhancement
