### ISSUE TITLE
Download Monitor CSV Importer Disappearing & Select All Not Working

### ISSUE THREAD

**Issue by MuttonTheChop** [WPChill/download-monitor#674] opened 2021-04-15 15:55 UTC
Hello!

We are able to install the CSV Importer plugin without issue, but after using the import functionality several times, the plugin disappears altogether. This has happened 3 times now. I did reach out to FlyWheel, or host, but they don't see any issues on their end. 

Also, after importing a CSV, when I view the full list, the "Select All" column doesn't actually select anthing.

Can you help? Thank you!

**Comment by razvanaldea89** [comment] 2022-03-09 13:14
@TeoAlex please check if this when we are approaching release v4.5.8

**Comment by TeoAlex** [comment] 2022-03-21 09:33
Tested multiple imports and could not reproduce the "dissapearing plugin" issue.
Also tested the "Select All" functionality and it works.
@MuttonTheChop can you give us some extra details please? What do you mean when you say "plugin disappears altogether"; it vanishes from Dashboard>Plugins page?

**Comment by razvanaldea89** [comment] 2022-03-22 13:45
Can't replicate this either

**Comment by razvanaldea89** [comment] 2022-03-24 05:50
Going to close this. If OP comes back with details will reopen it

**Closed by razvanaldea89** 2022-03-24 05:50 UTC
Labels: Bug, can't replicate
