### ISSUE TITLE
Shop, Products

### ISSUE THREAD

**Issue by weblint** [WPChill/download-monitor#797] opened 2021-12-03 12:31 UTC
![image](https://user-images.githubusercontent.com/16798922/144602575-2ca81a56-2271-4773-b15c-15cb1082840e.png)
If products contain an entry in the "Text excerpt" entry, the button also displays  extra tags p /p.

![image](https://user-images.githubusercontent.com/16798922/144602980-9f839be0-34c8-4912-bf22-a3fb4e7f2c9a.png)

**Comment by cristianraiber** [comment] 2021-12-03 13:37
It looks like a wrong sanitization here

**Comment by TeoAlex** [comment] 2022-01-18 12:39
This is a duplicate of https://github.com/WPChill/download-monitor/issues/790.

**Closed by TeoAlex** 2022-01-18 12:39 UTC
Labels: Bug, Duplicate
