### ISSUE TITLE
 PHP Warnings

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#986] opened 2022-07-15 09:44 UTC
**Describe the bug**
I am getting following PHP Warnings after installing this plugin on my local.

[13-Jul-2022 11:54:07 UTC] PHP Warning:  Undefined array key "icon" in /var/www/wp-content/plugins/download-monitor/src/Admin/Settings/Page.php on line 621
[13-Jul-2022 11:54:07 UTC] PHP Warning:  Undefined array key "icon_color" in /var/www/wp-content/plugins/download-monitor/src/Admin/Settings/Page.php on line 622
[13-Jul-2022 11:54:07 UTC] PHP Warning:  Undefined array key "text" in /var/www/wp-content/plugins/download-monitor/src/Admin/Settings/Page.php on line 623

I am using PHP 8 for local development.

https://wordpress.org/support/topic/about-php-warnings/

**Comment by razvanaldea89** [comment] 2022-07-19 06:07
Duplicate of https://github.com/WPChill/download-monitor/issues/979

**Closed by razvanaldea89** 2022-07-19 06:07 UTC
Labels: Bug
